In [0]:
import numpy as np

In [0]:
arr = np.array([[1,2,3],[4,5,6]])

In [0]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
# array dimension
arr.ndim

2

In [0]:
arr.shape

(2, 3)

In [0]:
arr.size

6

In [0]:
a = np.zeros([2,3])

In [0]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
a = np.empty([1,2])

In [0]:
a = np.full([3,3],6,dtype='int')

In [0]:
a

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [0]:
# print the value 1 to 30 with a difference of 5
a1 = np.arange(0,30,5)

In [0]:
a1

array([ 0,  5, 10, 15, 20, 25])

In [0]:
g = np.linspace(0,5,10)

In [0]:
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [0]:
ar = np.array([[2,1,4,5],[2,6,1,7],[1,2,3,4]])
ar

array([[2, 1, 4, 5],
       [2, 6, 1, 7],
       [1, 2, 3, 4]])

In [0]:
new_ar = ar.reshape(2,2,3)
new_ar

array([[[2, 1, 4],
        [5, 2, 6]],

       [[1, 7, 1],
        [2, 3, 4]]])

In [0]:
ar[:,1::2]

array([[1, 5],
       [6, 7],
       [2, 4]])

In [0]:
new = ar.T

In [0]:
ar.size

12

In [0]:
new

array([[2, 2, 1],
       [1, 6, 2],
       [4, 1, 3],
       [5, 7, 4]])

In [0]:
new[1,::2]

array([1, 2])

In [0]:
a = np.vstack([2,3,4])
a

array([[2],
       [3],
       [4]])

In [0]:
b = np.hstack([2,4,3])
b

array([2, 4, 3])

In [0]:
c = np.column_stack([1,3,5])
d = np.column_stack([7,5,6])
e = c+d
e

array([[ 8,  8, 11]])

In [0]:
z = np.arange(0,9)
z


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
A = np.array([z , np.ones(9)])
A

array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])